# Generated by Django 6.0.5 on 2026-05-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
